version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: screenshothis-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: screenshothis-access-key
      MINIO_ROOT_PASSWORD: screenshothis-secret-key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
