packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - puppeteer
  - sharp
  - unrs-resolver
