/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MarketingImport } from './routes/_marketing'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as MarketingIndexImport } from './routes/_marketing/index'
import { Route as AppScreenshotsImport } from './routes/_app/screenshots'
import { Route as AppPlaygroundImport } from './routes/_app/playground'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AuthRegisterSplatImport } from './routes/_auth/register.$'
import { Route as AuthLoginSplatImport } from './routes/_auth/login.$'

// Create/Update Routes

const MarketingRoute = MarketingImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const MarketingIndexRoute = MarketingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)

const AppScreenshotsRoute = AppScreenshotsImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => AppRoute,
} as any)

const AppPlaygroundRoute = AppPlaygroundImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AuthRegisterSplatRoute = AuthRegisterSplatImport.update({
  id: '/register/$',
  path: '/register/$',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginSplatRoute = AuthLoginSplatImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MarketingImport
      parentRoute: typeof rootRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundImport
      parentRoute: typeof AppImport
    }
    '/_app/screenshots': {
      id: '/_app/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof AppScreenshotsImport
      parentRoute: typeof AppImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexImport
      parentRoute: typeof MarketingImport
    }
    '/_auth/login/$': {
      id: '/_auth/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof AuthLoginSplatImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register/$': {
      id: '/_auth/register/$'
      path: '/register/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof AuthRegisterSplatImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppScreenshotsRoute: typeof AppScreenshotsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppScreenshotsRoute: AppScreenshotsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginSplatRoute: typeof AuthLoginSplatRoute
  AuthRegisterSplatRoute: typeof AuthRegisterSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginSplatRoute: AuthLoginSplatRoute,
  AuthRegisterSplatRoute: AuthRegisterSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MarketingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/playground': typeof AppPlaygroundRoute
  '/screenshots': typeof AppScreenshotsRoute
  '/': typeof MarketingIndexRoute
  '/login/$': typeof AuthLoginSplatRoute
  '/register/$': typeof AuthRegisterSplatRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/playground': typeof AppPlaygroundRoute
  '/screenshots': typeof AppScreenshotsRoute
  '/': typeof MarketingIndexRoute
  '/login/$': typeof AuthLoginSplatRoute
  '/register/$': typeof AuthRegisterSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/playground': typeof AppPlaygroundRoute
  '/_app/screenshots': typeof AppScreenshotsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_auth/login/$': typeof AuthLoginSplatRoute
  '/_auth/register/$': typeof AuthRegisterSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/playground'
    | '/screenshots'
    | '/'
    | '/login/$'
    | '/register/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/dashboard'
    | '/playground'
    | '/screenshots'
    | '/'
    | '/login/$'
    | '/register/$'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_marketing'
    | '/_app/dashboard'
    | '/_app/playground'
    | '/_app/screenshots'
    | '/_marketing/'
    | '/_auth/login/$'
    | '/_auth/register/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_auth",
        "/_marketing"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/dashboard",
        "/_app/playground",
        "/_app/screenshots"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login/$",
        "/_auth/register/$"
      ]
    },
    "/_marketing": {
      "filePath": "_marketing.tsx",
      "children": [
        "/_marketing/"
      ]
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/_app/playground": {
      "filePath": "_app/playground.tsx",
      "parent": "/_app"
    },
    "/_app/screenshots": {
      "filePath": "_app/screenshots.tsx",
      "parent": "/_app"
    },
    "/_marketing/": {
      "filePath": "_marketing/index.tsx",
      "parent": "/_marketing"
    },
    "/_auth/login/$": {
      "filePath": "_auth/login.$.tsx",
      "parent": "/_auth"
    },
    "/_auth/register/$": {
      "filePath": "_auth/register.$.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
